name: Update Profile Bio in README

on:
  push:
    branches: [main]
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-bio:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Convert bio to table and update README
        uses: ./
        with:
          user: ${{ github.actor }}
          github_token: ${{ github.token }}
          files: 'README.md'
          placeholder: '{{github_profile_bio}}'

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --staged --quiet || git commit -m "chore: update profile bio table"
          git push
